use_default_settings: true

server:
  secret_key: "__SEARXNG_SECRET__"
  bind_address: "0.0.0.0"
  port: 8080
  public_instance: false
  image_proxy: false
  method: GET

search:
  formats:
    - html
    - json
